### ISSUE TITLE
With Python and C++: imenu-anywhere--candidates-from-entry: Wrong type argument:

### ISSUE THREAD

**Issue by rdiaz02** [vspinu/imenu-anywhere#11]
Simple example: I create a single python file (call it f2.py), and I make sure it is the only buffer:
a = 24
print(a)

and whenever I try to use imenu-anywhere I get 

imenu-anywhere--candidates-from-entry: Wrong type argument: integer-or-marker-p, #<overlay from 1 to 7 in f2.py>

This does not happen with R (or elisp), but similar problems happen with C++.

**Comment by vspinu** [comment]
This one was fixed a long time ago. I am sorry, I probably have missed this report and didn't reply.
