### ISSUE TITLE
requires helm without requiring it

### ISSUE THREAD

**Issue by ctanis** [vspinu/imenu-anywhere#17]
Latest update will not load if helm is not installed.

**Comment by vspinu** [comment]
Hm. That's strange, helm part was uplifted a bit but I don't see how it could affect the loading process. 

I will check asap.

**Comment by xuchunyang** [comment]
It's my fault. I'm working it.

**Comment by vspinu** [comment]
@xuchunyang thanks. It's `helm-build-sync-source`. Maybe we can do it in `(eval-after-load "helm" )`.

**Comment by xuchunyang** [comment]
Should be fixed in #18
