### ISSUE TITLE
 Invalid function: helm-build-sync-source 

### ISSUE THREAD

**Issue by psibi** [vspinu/imenu-anywhere#20]
`imenu-anywhere` makes latest `helm` unable to use. See more details here: https://github.com/emacs-helm/helm/issues/1051

**Comment by xuchunyang** [comment]
How to reproduce?

**Comment by psibi** [comment]
Have this in `init.el`:

    (require 'helm-config)
        (helm-mode 1)

    (use-package imenu-anywhere
       :ensure t)

I guess this should be reproducible even without `use-package`

**Comment by xuchunyang** [comment]
I still don't know exactly how to reproduce. I'm using latest helm and imenu-anywhere as well. I guess there is something wrong in your personal Emacs conf.

**Comment by vspinu** [comment]
I cannot reproduce that either. I don't have use-package in my emacs but with 

```
    (package-initialize)
    (require 'helm-config)
    (helm-mode 1)
    (require 'imenu-anywhere) 
```

everything works as expected. 

The only explanation I can think of is that you are using an old version of helm.el or helm-source.el which don't contain `helm-build-sync-source`.

**Comment by psibi** [comment]
Ok, I commented my entire `init.el` file and placed this in my `init.el` file:

    (package-initialize)
    (require 'helm-config)
    (helm-mode 1)
    (require 'imenu-anywhere)

And that brings back the error:

    Invalid function: helm-build-sync-source

These are the versions I'm using:

Emacs version: 24.5.2
imenu-anywhere     20150523.537
helm               20150610.955

Those 2015.... are the version show in Package mode. Let me know if any further details are required.

**Comment by xuchunyang** [comment]
How about using a fresh Emacs conf and package installation, for example, backup your `~/.emacs.d` and make a new one and with the following as your `init.el`:

```lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)

(require 'helm-config)
(helm-mode 1)

(require 'imenu-anywhere)
```

and then install `helm` and `imenu-anywhere` by using `package-install` (invoke `package-refresh-contents` firstly if needs)

**Comment by psibi** [comment]
Thanks, it indeed works when I installed a fresh version. Then I tried again with the backup-ed ~/.emacs.d configuration (which was earlier causing trouble), it again showed me the error. Then I deleted the `helm` package and updated it to the following version: 

helm               20150614.301

And then it started working. Thanks @xuchunyang and @vspinu for the help!
