### ISSUE TITLE
projectile support

### ISSUE THREAD

**Issue by blaenk** [vspinu/imenu-anywhere#21]
This would be great if you could restrict it to only files that are in the same mode _and_ are in the same projectile project, to avoid seeing entries from other projects, which may be possible especially if you use emacs daemon.

Perhaps that is out of the scope of this project. Just thought I'd bring it up.

**Comment by vspinu** [comment]
This makes a lot of sense. I am a projectile user myself. I think it should also disregard mode boundary. That is, for projects with multiple languages, mode should be irrelevant.

How do you see the UI?  I would like to have a rotation key inside ido or helm menus, such that you can switch between different contexts (same mode -> all relevant modes -> all projects modes).

**Comment by blaenk** [comment]
Yeah that'd be cool. Not sure about the ui sorry. I'm new to emacs myself, and I use helm-imenu so I'm not sure if the ui would apply (would such a thing work with this?).

**Comment by vspinu** [comment]
Both ido and helm have hook that could be used to bind a key, but I am not that sure about the filtering of the candidates in the middle of the query.

**Comment by Dickby** [comment]
Projectile support would be nice!
If possible for all projectile files, instead of just open buffers.

**Comment by vspinu** [comment]
> Projectile support would be nice!

Yes. I am finally getting down to it.

> If possible for all projectile files, instead of just open buffers.

This is hard and not an intention of imenu. I think being able to open just a few files in a  project and limit yourself to only those is an advantage rather than a drawback of imenu-anywhere.

Tags is what you need for files on disc (etags, gtags).

**Comment by bbatsov** [comment]
Guess all you need is `projectile-project-buffers`.

**Comment by vspinu** [comment]
I have rewritten the package. There is now a flexible system of configuring reachable buffers. Same project buffers are reachable by default now. See `imenu-anywhere-buffer-filter-functions`.

**Comment by blaenk** [comment]
Very cool!
