### ISSUE TITLE
Add ivy support

### ISSUE THREAD

**Issue by sooheon** [vspinu/imenu-anywhere#30]
ido and helm are still the most popular for completion, but many people find swiper a nice alternative. Would you consider adding this as an alternative as well?

**Comment by vspinu** [comment]
Yes. This is the plan. I want to isolate core functionality in a standalone package and then provide extra  packages for helm and ivy.

**Comment by sooheon** [comment]
That sounds like the right way to go. Thanks for the work on the package!

**Comment by vspinu** [comment]
Actually it turned to be an one-liner so I have decided to keep it within the same package. The new function is called `ivy-imenu-anywhere`.
