### ISSUE TITLE
 imenu-anywhere not worked with set helm-imenu-fuzzy-match variable.

### ISSUE THREAD

**Issue by zw963** [vspinu/imenu-anywhere#31]
Helm offer a `helm-imenu-in-all-buffers`, work familiar with `helm-anywhere`.

when set helm-imenu-fuzzy-match t,  helm-anywhere should support fuzzy match
as helm-imenu-in-all-buffers.

Thanks

**Comment by zw963** [comment]
Worked.

**Comment by zw963** [comment]
reboot emacs deamon, get following error:

Symbol's value as variable is void: helm-imenu-fuzzy-match

**Comment by zw963** [comment]
variable `helm-imenu-fuzzy-match` only exist in `helm-imenu`.

I think we need offer a default value for this variable before
helm automatic require helm-imenu to make effect.

**Comment by vspinu** [comment]
Should be fixed now.

**Comment by zw963** [comment]
Fixed, Though, just want remind guys which use fuzzy, we must need load this package like following to enable helm-imenu fuzzy in helm.

```cl
(setq helm-imenu-fuzzy-match t)
(require 'imenu-anywhere)
```

Though this wired for me, because `imenu-anywhere` settings as a ido enhanced package,
it set before my helm settings, this may confuse someone which found his imenu fuzzy not
 work well.

I think non helm builtin  package should permit setq a variable after manually
require package. (just like helm-swoop, following code fuzzy is worked, though,
helm-swoop-use-fuzzy-match is a new introduced variable)
```cl
(require 'helm-swoop)
(setq helm-swoop-use-fuzzy-match t)
```

Here have some discuss about this.

https://github.com/emacs-helm/helm/issues/1486
