### ISSUE TITLE
imenu-anywhere-pkg can not Compiling at ubuntu-16.04-server-amd64

### ISSUE THREAD

**Issue by Lescpsn** [vspinu/imenu-anywhere#34]
Compiling file /home/carhj/.emacs.d/elpa/imenu-anywhere-20160520.320/imenu-anywhere-pkg.el at Tue Jun 21 04:07:16 2016                                                     
Entering directory `/home/carhj/.emacs.d/elpa/imenu-anywhere-20160520.320/'                                                                                                
^L                                                                                                                                                                         
Compiling file /home/carhj/.emacs.d/elpa/imenu-anywhere-20160520.320/imenu-anywhere.el at Tue Jun 21 04:07:16 2016                                                         
imenu-anywhere.el:230:1:Error: Autoloading failed to define function helm-build-sync-source

**Comment by vspinu** [comment]
You are probably using very old helm. `helm-build-sync-source` is defined in `helm-source.el`. 

You should re-install helm first and then re-install imenu-anywhere.

**Comment by vspinu** [comment]
Ok. I see the problem. Looking into it right now.
