### ISSUE TITLE
display file name / path in the list

### ISSUE THREAD

**Issue by rsuhada** [vspinu/imenu-anywhere#35]
Thank you for the excellent package - it makes searching so smooth!

What would be helpful for me is if also the file name (optionally full path) could be also displayed. There are often similar tags and it would be helpful to know which files are they coming from. Is this possible? 

I use the helm-imenu-anywhere interface.

Thank you!

**Comment by vspinu** [comment]
Indeed. Duplicated entries are not treated quite well yet. Not only in helm.
