### ISSUE TITLE
how to configure projectile support?

### ISSUE THREAD

**Issue by Wingie** [vspinu/imenu-anywhere#37]
in regard to #21 
is it possible to reach all buffers of the same mode in a particular projectile project?
can you help in syntax of the configuration for a beginner?

**Comment by vspinu** [comment]
The projectile support is active by default. You should be able to reach all buffers of any mode inside a project. 

You can filter accessible buffers arbitrarily by placing custom functions into `imenu-anywhere-buffer-filter-functions`. If you don't like `imenu-anywhere-same-mode-p`, simply remove it from that list.

**Comment by Wingie** [comment]
Ah yes. It does do so. sorry.
I was testing it with trying to reach files with the same extension in my projectile tree.
do you have any suggestions on how to get this working?

**Comment by vspinu** [comment]
The aim of imenu-anywhere is to reach open buffers, that's different from reaching files. Two options to reach files that I am aware of are:

  - `projectile-find-file`
  - `helm-projectile` (which I personally use)

There are some variations to search accros projects as well: `helm-projects-find-files`, `projectile-find-file-in-known-projects`.
