### ISSUE TITLE
Enhancement: Navigate in all files in current/selected git or projectile project

### ISSUE THREAD

**Issue by fractus** [vspinu/imenu-anywhere#38]
think it would a great extension if you could navigate across all files under a git project, provide project-level navigation rather than open buffers navigation.

**Comment by vspinu** [comment]
Projectile support is activated by default. See `imenu-anywhere-buffer-filter-functions`.  

Are you looking for something more specific?

**Comment by fractus** [comment]
True. I was thinking about a rescan of all projectile files [for particular mode], not only the ones currently open. This may be beyond the scope of this project though.

**Comment by vspinu** [comment]
> I was thinking about a rescan of all projectile files 

This is precisely what is happening right now. Have you tried?

**Comment by vspinu** [comment]
Ah. You mean files, not buffer. Indeed. That's beyond the scope of this project.
