### ISSUE TITLE
company-coq integration

### ISSUE THREAD

**Issue by vzaliva** [vspinu/imenu-anywhere#41]
It is more a question than an issue...

I am using imenu-everywehere with [Company-Coq](https://github.com/cpitclaudel/company-coq).
The menu shown now display SGML-like tags. See attached screenshot. This is not very readable. I would like to customize it for better display.

![screenshot_20191106_130316](https://user-images.githubusercontent.com/86581/68337653-d1e82300-0095-11ea-9b0d-07ceb5e3ce25.png)

For example, instead of `foo/\_<Inductive\>` I would like to see `Inductive foo`.

I can try to patch produce a patch for this myself, but I need to understand better where it needs to be fixed: on company-coq or imenu-anywhere side?

**Comment by vzaliva** [comment]
Tagging @cpitclaudel in case he have any thoughts....

**Comment by cpitclaudel** [comment]
No clue on my side :)

**Comment by vzaliva** [comment]
I was digging though source code and so far have not been able to figure out where `imenu` takes list of definitions from PG/Company-Coq mode buffers.  I do not see calls to `imenu-create-index-function` like it is done in Haskell, Merlin and Org modes. So I guess it uses default index function implemented in buffer-generic way. Perhaps using "syntax tables"?

**Comment by vspinu** [comment]
Sorry for late response. I somehow missed the notification.

This issue is not on `imenu-anywhere` side. It's just an interface to each mode's imenu implementation.  The reason for those ugly `\\_` is because they are encoded in `imenu-generic-expression`. If you look for those in `coq-mode` it will look like this:

```el
(("\\_<Local\\S-+Axiom\\_>" "\\_<Local\\s-+Axiom\\_>\\s-+\\(\\_<\\(?:\\sw\\|\\s_\\)+\\_>\\)" 1)
 ("\\_<Local\\S-+Axioms\\_>" "\\_<Local\\s-+Axioms\\_>\\s-+\\(\\_<\\(?:\\sw\\|\\s_\\)+\\_>\\)" 1)
 ("\\_<Axiom\\_>" "\\_<Axiom\\_>\\s-+\\(\\_<\\(?:\\sw\\|\\s_\\)+\\_>\\)" 1)
 ("\\_<Axioms\\_>" "\\_<Axioms\\_>\\s-+\\(\\_<\\(?:\\sw\\|\\s_\\)+\\_>\\)" 1)
 ("\\_<Global\\S-+Variable\\_>" "\\_<Global\\s-+Variable\\_>\\s-+\\(\\_<\\(?:\\sw\\|\\s_\\)+\\_>\\)" 1)

```
This is surely not correct. For instance in SQL it looks like:

```el
(("Rules/Defaults" "^\\s-*create\\s-+\\(?:\\w+\\s-+\\)*\\(?:rule\\|default\\)\\(?:if\\s-+not\\s-+exists\\s-+\\)?\\s-+\\(\\(?:\\w+\\s-*[.]\\s-*\\)*\\w+\\)" 1)
 ("Sequences" "^\\s-*create\\s-+\\(?:\\w+\\s-+\\)*sequence\\s-+\\(?:if\\s-+not\\s-+exists\\s-+\\)?\\(\\(?:\\w+\\s-*[.]\\s-*\\)*\\w+\\)" 1)
 ("Triggers" "^\\s-*create\\s-+\\(?:\\w+\\s-+\\)*trigger\\s-+\\(?:if\\s-+not\\s-+exists\\s-+\\)?\\(\\(?:\\w+\\s-*[.]\\s-*\\)*\\w+\\)" 1)
 ("Functions" "^\\s-*\\(?:create\\s-+\\(?:\\w+\\s-+\\)*\\)?function\\s-+\\(?:if\\s-+not\\s-+exists\\s-+\\)?\\(\\(?:\\w+\\s-*[.]\\s-*\\)*\\w+\\)" 1)
 ("Procedures" "^\\s-*\\(?:create\\s-+\\(?:\\w+\\s-+\\)*\\)?proc\\(?:edure\\)?\\s-+\\(?:if\\s-+not\\s-+exists\\s-+\\)?\\(\\(?:\\w+\\s-*[.]\\s-*\\)*\\w+\\)" 1)
...
```

It looks like it comes from `coq-generic-expression` which see. 

You can reproduce the problem without `imenu-anywhere`, just do `M-x imenu` and you should see the ugly symbols. 

@cpitclaudel would you like a dedicated issue on `proof-general` for this?

**Comment by vzaliva** [comment]
Thanks for the feedback. It looks like a [proof-general](https://github.com/ProofGeneral/PG), not [company-coq]() issue. Perhaps we should open a ticket for them? Not sure how to correctly formulate it and will appreciate a little help with that.

From ProofGeneral.info:

> The Emacs package 'imenu' (Index Menu) provides a menu built from the
> names of entities (e.g., theorems, definitions, etc) declared in a
> buffer.  This allows easy navigation within the file.  Proof General
> configures both packages automatically so that you can quickly jump to
> particular proofs in a script buffer.
> 
> (Developers note: the automatic configuration is done with the settings
> 'proof-goal-with-hole-regexp' and 'proof-save-with-hole-regexp'.  Better
> configuration may be made manually with several other settings, see the
> Adapting Proof General manual for further details).
> 
> To use Imenu, select the option
>              Proof-General -> Quick Options -> Minor Modes -> Index Menu
> This adds an "Index" menu to the main menu bar for proof script buffers.
> You can also use 'M-x imenu' for keyboard-driven completion of tags
> built from names in the buffer.
>

**Comment by vzaliva** [comment]
Thanks for helping to diagnose this. I have reported to PG team and closing this issue.
