### ISSUE TITLE
Is it possible to filter out local variables and only display global variables functions etc

### ISSUE THREAD

**Issue by xqliu** [vspinu/imenu-anywhere#42]
Hi,

Thanks for the package, 

I would like to know that,

Is it possible to filter out local variables and only display global variables functions etc?

Thanks.

**Comment by vspinu** [comment]
Which language is this? 

The imenu lookup is controlled by each mode individually. See `imenu-generic-expression` in the mode you are interested in. By tweaking those you should be able to achieve anything you want. `imenu-anywhere` cannot do it for you.
